### ISSUE TITLE
PIP dependency conflict?

### ISSUE THREAD

**Issue by roschler** [saharmor/dalle-playground#76] opened 2022-06-16 21:58 UTC
When I run all cells on the Google Colab project, I see this error:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
```
Any way to fix it?  I'm running on the free version of Google Colab, perhaps the demo no longer works on the free version?

**Comment by saharmor** [comment] 2022-06-17 01:09
Duplicate of https://github.com/saharmor/dalle-playground/issues/54 
This shouldn't prevent you from generating images.

**Closed by saharmor** 2022-06-17 01:09 UTC
