### ISSUE TITLE
Docker install doesn't set up localtunnel

### ISSUE THREAD

**Issue by rahimnathwani** [saharmor/dalle-playground#18] opened 2022-06-06 20:48 UTC
I tried to follow the instructions to run with docker-compose, but:

- The web interface wouldn't let me enter `http://localhost:8080/` as the backend URL, and
- Neither of the `DockerFile`s sets up a tunnel

I ran these commands at a terminal:
```
sudo npm install -g localtunnel
lt --port 8080
```

I'm not sure of the best place for these, because:
- The backend service is based on an image that doesn't have node (AFAIK)
- The commands don't really relate to the interface service (but that service's image does have node)

**Comment by saharmor** [comment] 2022-06-09 05:12
Hi @rahimnathwani, loca.lt was down but it's up again. Closing this issue for now but feel free to reopen if the error persists.

**Closed by saharmor** 2022-06-09 05:12 UTC

**Comment by rahimnathwani** [comment] 2022-06-09 05:35
@saharmor I think the issue was not about loca.lt being down. The `lt` command is missing from the docker-compose flow. The only mention of `lt` in the repo is in the Jupyter notebook: https://github.com/saharmor/dalle-playground/search?q=lt
![image](https://user-images.githubusercontent.com/891558/172771922-073d6d07-17f3-4c7f-b330-2530083de4cc.png)

**Comment by cHemingway** [comment] 2022-06-11 22:05
I can confirm I have what looks like the same problem, there is no localtunnel URL output by either of the containers, and I can't see either dockerfile set this up either.

I tried to run it localtunnel on the `dalle-backend` container but the version of node the image's ubuntu 20.04 ships with (10.19) is too old to run localtunnel, one of the dependencies for localtunnel (yargs) doesn't support Node<12
```
Error: yargs supports a minimum Node.js version of 12. Read our version support policy: https://github.com/yargs/yargs#supported-nodejs-versions
```
